calapp/urls.py
from django.urls import path
from . import views
# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    # path('login', auth_views.login, name="login"),
    # path('logout', auth_views.logout, name="logout"),
    # path('signup', views.signup, name="signup"),
    path('entry/<int:pk>', views.details, name="details"),
    path('entry/add', views.AddView.as_view(), name="add"),
    path('dashboard/entry/delete/<int:pk>', views.delete, name="delete"),
]

moviesapp/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.MovieListView.as_view(), name='index'),
    path('studio/', views.StudioListView.as_view(), name='studioindex'),
    path('studio/<slug>/', views.StudioDetailView.as_view(),
         name='studiodetail'),
    path('director/', views.DirectorListView.as_view(), name='directorindex'),
    path('director/<int:pk>/', views.DirectorDetailView.as_view(),
         name='directordetail'),
    path('genre/', views.GenreListView.as_view(), name='genreindex'),
    path('genre/<slug>/', views.GenreDetailView.as_view(), name='genredetail'),
    path('<slug>/', views.MovieDetailView.as_view(), name='detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('places/', include('placesapp.urls')),
    path('events/', include('calapp.urls')),
    path('movies/', include('moviesapp.urls')),
    path('music/', include('musicapp.urls')),
    path('forum/', include('forumapp.urls'))
]

moviesapp/models.py
from django.db import models
from django.template.defaultfilters import slugify

gender = (
    ('male', 'Male'),
    ('female', 'Female'),
    ('other', 'Other'),
)


class Movie(models.Model):
    title = models.CharField(max_length=200)
    prefix = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=200)
    slug = models.SlugField(blank=True)
    directors = models.ManyToManyField("Director", verbose_name=("Director"),
                                       related_name='moviedirector')
    studio = models.ForeignKey("Studio", verbose_name=("Studio"),
                               on_delete=models.CASCADE,
                               related_name='moviestudio')
    release_date = models.DateField(auto_now=False, auto_now_add=False)
    cover_image = models.URLField(max_length=200)
    review = models.TextField()
    genre = models.ManyToManyField("Genre", verbose_name=("Genre"),
                                   related_name='moviegenre')
    asin = models.CharField(max_length=50)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Movie, self).save(*args, **kwargs)

    @property
    def amazon_url(self, *args, **kwargs):
        return 'http://amazon.com/blablablaa/{}'.format(self.slug)

    def __str__(self):
        return self.title


class Studio(models.Model):
    title = models.CharField(max_length=200)
    prefix = models.CharField(max_length=50)
    website = models.URLField(max_length=200)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Studio, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Genre(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Genre, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Director(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, blank=True)
    phone = models.IntegerField()
    birth_date = models.DateField(auto_now=False, auto_now_add=False)
    website = models.URLField(max_length=200)
    gender = models.CharField(
        choices=gender,
        default='male',
        max_length=6
    )

    def __str__(self):
        return '{} {} {}'.format(self.first_name,
                                 self.middle_name, self.last_name)

moviesapp/views.py
from django.views import generic
from .models import Movie, Genre, Director, Studio


class MovieListView(generic.ListView):
    model = Movie
    template_name = "movies/index.html"
    context_object_name = 'movies'


class MovieDetailView(generic.DetailView):
    model = Movie
    template_name = "movies/detail.html"
    context_object_name = 'movie'


class StudioListView(generic.ListView):
    model = Studio
    template_name = "movies/studioindex.html"
    context_object_name = 'studios'


class StudioDetailView(generic.DetailView):
    model = Studio
    template_name = "movies/studiodetail.html"
    context_object_name = 'studio'


class DirectorListView(generic.ListView):
    model = Director
    template_name = "movies/directorindex.html"
    context_object_name = 'directors'


class DirectorDetailView(generic.DetailView):
    model = Director
    template_name = "movies/directordetail.html"
    context_object_name = 'director'


class GenreListView(generic.ListView):
    model = Genre
    template_name = "movies/genreindex.html"
    context_object_name = 'genres'


class GenreDetailView(generic.DetailView):
    model = Genre
    template_name = "movies/genredetail.html"
    context_object_name = 'genre'

moviesapp/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,600" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'movies/css/style.css' %}">
    {% block head %}
    {% endblock head %}
</head>
<body>
    <nav class="navbar has-background-black-ter has-text-white">
<div class="container">
  <div class="navbar-brand">
    <a class="navbar-item" class="is-size-2" href="{% url 'movies:index' %}">
      <h4 class="is-size-3">Movies</h4>
    </a>
    <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-end">
      <a href="{% url 'movies:index' %}" class="navbar-item">Movies</a>
      <a href="{% url 'movies:directorindex' %}" class="navbar-item">Directors</a>
      <a href="{% url 'movies:studioindex' %}" class="navbar-item">Studios</a>
      <a href="{% url 'movies:genreindex' %}" class="navbar-item">Genres</a>
    </div>
  </div>
</div>
</nav>
    {% block content %}

    {% endblock content %}
<script>
document.addEventListener('DOMContentLoaded', () => {

  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach( el => {
      el.addEventListener('click', () => {

        // Get the target from the "data-target" attribute
        const target = el.dataset.target;
        const $target = document.getElementById(target);

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }

});
</script>
</body>
</html>

moviesapp/templates/movies/detail.html
{% extends 'movies/base.html' %}

{% block head %}

    <style>
        html,body{
            background:hsl(0, 0%, 14%);
            color: #fff;
        }
        strong{
            color: #6D5BC8;
        }
    </style>

{% endblock head %}

{% block content %}

 <section>
    <div class="container">
        <div class="columns  is-vcentered">
            <div class="column">
                <img src="{{movie.cover_image}}" class="image" alt="">
            </div>
            <div class="column has-text-white">
                <strong>Name : </strong> {{movie.title}} <br>
                <strong>Subtitle : </strong> {{movie.subtitle}} <br>    
                <strong>Directors: </strong> {% for director in movie.directors.all %}{{director}} {% endfor %}<br>
                <strong>Studio : </strong> {{movie.studio.title}} <br>
                <strong>Release Date : </strong> {{movie.release_date}} <br>
                <strong>Genre : </strong> {% for genre in movie.genre.all %}{{genre.title}} {% endfor %} <br>
                <strong>ASIN : </strong> {{movie.asin}} <br>
                <strong>Review : </strong> <p>{{movie.review}}</p> <br>
                <strong>Amazon url : </strong> <p>{{movie.amazonurl}}</p> <br>
            </div>
        </div>
    </div>
 </section>

{% endblock content %}

moviesapp/templates/movies/directordetail.html
{% extends 'movies/base.html' %}

{% block head %}

    <style>
        html,body{
            background:hsl(0, 0%, 14%);
            color: #fff;
        }
        strong{
            color: #6D5BC8;
        }
    </style>

{% endblock head %}

{% block content %}

 <section>
    <div class="container">
        <div class="columns  is-vcentered">
            <div class="column has-text-white">
                <strong>Name : </strong> {{director}} <br>
                <strong>Phone : </strong> {{director.phone}} <br>    
                <strong>Birth Date : </strong> {{director.birth_date}} <br>  
                <strong>Gender : </strong> {{director.gender}} <br>  
                <strong>website : </strong> {{director.website}} <br> 
                <strong>Movies : </strong> {% for movie in director.moviedirector.all %} {{movie.title}} {% endfor %} <br> 
            </div>
        </div>
    </div>
 </section>

{% endblock content %}

moviesapp/templates/movies/directorindex.html
{% extends 'movies/base.html' %}

{% block head %}

    <style>
        html,body{
            background:hsl(0, 0%, 14%);
            color: #fff;
        }
    </style>

{% endblock head %}

{% block content %}
<hr class="is-marginless">
    <section class="my-3">
        <div class="container">
            <div class="columns">
                {% for director in directors %}
                    <div class="column is-3">
                       <a href="{% url 'movies:directordetail' director.id %}">
                            <div class="box border">
                                <h4><strong class="my-2 colordark">{{director}}</strong></h4>
                            </div>
                       </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock content %}

moviesapp/templates/movies/genredetail.html
{% extends 'movies/base.html' %}

{% block head %}

    <style>
        html,body{
            background:hsl(0, 0%, 14%);
            color: #fff;
        }
        strong{
            color: #6D5BC8;
        }
    </style>

{% endblock head %}

{% block content %}

 <section>
    <div class="container">
        <div class="columns  is-vcentered">
            <div class="column has-text-white">
                <strong>Name : </strong> {{genre.title}} <br>
                <strong>Movies : </strong> {% for movie in genre.moviegenre.all %} {{movie.title}} {% endfor %} <br> 
            </div>
        </div>
    </div>
 </section>

{% endblock content %}

moviesapp/templates/movies/genreindex.html
{% extends 'movies/base.html' %}

{% block head %}

    <style>
        html,body{
            background:hsl(0, 0%, 14%);
            color: #fff;
        }
    </style>

{% endblock head %}

{% block content %}
<hr class="is-marginless">
    <section class="my-3">
        <div class="container">
            <div class="columns">
                {% for genre in genres %}
                    <div class="column is-3">
                       <a href="{% url 'movies:genredetail' genre.slug %}">
                            <div class="box border">
                                <h4><strong class="my-2 colordark">{{genre.title}}</strong></h4>
                            </div>
                       </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock content %}

moviesapp/templates/movies/index.html
{% extends 'movies/base.html' %}

{% block head %}

    <style>
        html,body{
            background:hsl(0, 0%, 14%);
            color: #fff;
        }
    </style>

{% endblock head %}

{% block content %}
<hr class="is-marginless">
    <section class="my-3">
        <div class="container">
            <div class="columns">
                {% for movie in movies %}
                    <div class="column is-3">
                       <a href="{% url 'movies:detail' movie.slug %}">
                            <div class="box border">
                                <img src="{{ movie.cover_image }}" class="img-fluid image" alt="">
                                <br>
                                <h4><strong class="my-2 colordark">{{movie.title}}</strong></h4>
                            </div>
                       </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock content %}

moviesapp/templates/movies/studiodetail.html
{% extends 'movies/base.html' %}

{% block head %}

    <style>
        html,body{
            background:hsl(0, 0%, 14%);
            color: #fff;
        }
        strong{
            color: #6D5BC8;
        }
    </style>

{% endblock head %}

{% block content %}

 <section>
    <div class="container">
        <div class="columns  is-vcentered">
            <div class="column has-text-white">
                <strong>Name : </strong> {{studio.title}} <br>
                <strong>Prefix : </strong> {{studio.prefix}} <br>    
                <strong>website : </strong> {{studio.website}} <br> 
                <strong>Movies : </strong> {% for movie in studio.moviestudio.all %} {{movie.title}} {% endfor %} <br> 
            </div>
        </div>
    </div>
 </section>

{% endblock content %}

moviesapp/templates/movies/studioindex.html
{% extends 'movies/base.html' %}

{% block head %}

    <style>
        html,body{
            background:hsl(0, 0%, 14%);
            color: #fff;
        }
    </style>

{% endblock head %}

{% block content %}
<hr class="is-marginless">
    <section class="my-3">
        <div class="container">
            <div class="columns">
                {% for studio in studios %}
                    <div class="column is-3">
                       <a href="{% url 'movies:studiodetail' studio.slug %}">
                            <div class="box border">
                                <h4><strong class="my-2 colordark">{{studio.title}}</strong></h4>
                            </div>
                       </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock content %}