calapp/urls.py
from django.urls import path
from . import views
# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    # path('login', auth_views.login, name="login"),
    # path('logout', auth_views.logout, name="logout"),
    # path('signup', views.signup, name="signup"),
    path('entry/<int:pk>', views.details, name="details"),
    path('entry/add', views.AddView.as_view(), name="add"),
    path('dashboard/entry/delete/<int:pk>', views.delete, name="delete"),
]

musicapp/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    path('', views.AlbumList.as_view(), name="album_list"),
    path('songs/', views.SongList.as_view(), name="song_list"),
    path('detail/<slug>', views.AlbumDetail.as_view(), name="album_detail"),
    path('bands/', views.BandList.as_view(), name="band_list"),
    path('band/detail/<int:pk>', views.BandDetail.as_view(),
         name="band_detail"),
    path('labels/', views.LabelList.as_view(), name="label_list"),
    path('label/detail/<int:pk>', views.LabelDetail.as_view(),
         name="label_detail"),
    path('genres/', views.GenreList.as_view(), name="genre_list"),
    path('genre/detail/<slug>', views.GenreDetail.as_view(),
         name="genre_detail"),
    path('song/detail/<slug>', views.SongDetail.as_view(), name="song_detail"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('places/', include('placesapp.urls')),
    path('events/', include('calapp.urls')),
    path('movies/', include('moviesapp.urls')),
    path('music/', include('musicapp.urls')),
    path('forum/', include('forumapp.urls'))
]

musicapp/models.py
from django.db import models
from django.template.defaultfilters import slugify


gender = (
    ('male', 'Male'),
    ('female', 'Female'),
    ('other', 'Other'),
)


class SlugMixin(models.Model):

    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(SlugMixin, self).save(*args, **kwargs)

    class Meta:
        abstract = True


class Track(SlugMixin):
    name = models.CharField(("Track Name"), max_length=100)
    band = models.ForeignKey("Band", on_delete=models.CASCADE,
                             blank=True, null=True, related_name="tracks")
    album = models.ForeignKey("Album", on_delete=models.CASCADE,
                              blank=True, null=True, related_name="tracks")
    song = models.FileField(upload_to="songs/", max_length=150)
    genre = models.ManyToManyField("Genre", related_name="tracks")

    def __str__(self):
        return self.name


class Album(SlugMixin):
    name = models.CharField(("Title"), max_length=50)
    prefix = models.CharField(max_length=50)
    asin = models.CharField(("ASIN"), max_length=10)
    band = models.ForeignKey("Band", on_delete=models.CASCADE,
                             blank=True, null=True, related_name="albums")
    label = models.ForeignKey("Label", on_delete=models.CASCADE,
                              blank=True, null=True, related_name="albums")
    cover_image = models.FileField(upload_to="images/", max_length=100)
    release_date = models.DateField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.name


class Genre(SlugMixin):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Label(models.Model):
    name = models.CharField(max_length=150)
    head_quarters = models.CharField(max_length=50)
    website = models.URLField(max_length=200)

    def __str__(self):
        return self.name


class Musician(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    gender = models.CharField(
        choices=gender,
        default='male',
        max_length=6
    )
    band = models.ForeignKey("Band", on_delete=models.CASCADE,
                             related_name="musicians")
    instrument = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Band(models.Model):
    name = models.CharField(max_length=50)
    genre = models.ManyToManyField("Genre", related_name="bands")
    website = models.URLField(max_length=200)

    def __str__(self):
        return self.name

musicapp/views.py
from django.views import generic
from .models import Album, Track, Band, Label, Genre


class AlbumList(generic.ListView):
    template_name = "music/index.html"
    model = Album
    context_object_name = 'albums'


class AlbumDetail(generic.DetailView):
    template_name = "music/detail.html"
    model = Album
    context_object_name = 'album'


class SongList(generic.ListView):
    template_name = "music/songlist.html"
    model = Track
    context_object_name = 'tracks'


class SongDetail(generic.DetailView):
    template_name = "music/songdetail.html"
    model = Track
    context_object_name = 'track'


class BandList(generic.ListView):
    template_name = "music/bandlist.html"
    model = Band
    context_object_name = 'bands'


class BandDetail(generic.DetailView):
    template_name = "music/banddetail.html"
    model = Band
    context_object_name = 'band'


class LabelList(generic.ListView):
    template_name = "music/labellist.html"
    model = Label
    context_object_name = 'labels'


class LabelDetail(generic.DetailView):
    template_name = "music/labeldetail.html"
    model = Label
    context_object_name = 'label'


class GenreList(generic.ListView):
    template_name = "music/genrelist.html"
    model = Genre
    context_object_name = 'genres'


class GenreDetail(generic.DetailView):
    template_name = "music/genredetail.html"
    model = Genre
    context_object_name = 'genre'

musicapp/templates/music/banddetail.html
{% extends 'music/base.html' %}


{% block content %}
<section>
<div class="container p-4 my-4 shadowy">

   <h3 class="text-primary text-center"> {{band}}</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Age</th>
      <th scope="col">Instrument</th>
    </tr>
  </thead>
  <tbody>
     
      {% for musician in band.musicians.all %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td><a href="">{{musician.name}}</a></td>
        <td><a href="">{{musician.age}}</a></td>
        <td>{{musician.instrument}}</td>
        
        
</tr>
      {% endfor %}

   
    

   
  </tbody>
</table>

</div>
</section>
{% endblock content %}

musicapp/templates/music/bandlist.html
{% extends 'music/base.html' %}


{% block content %}
<section>
<div class="container p-4 my-4 shadowy">

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Band</th>
      <th scope="col">Website</th>
      <th scope="col">Genre</th>
    </tr>
  </thead>
  <tbody>
      {% for band in bands %}
     <th scope="row">{{forloop.counter}}</th>
      <td><a href="{% url 'music:band_detail' band.id %}">{{band}}</a></td>
      <td>{{band.website}}</td>
      <td>{% for genre in band.genre.all %}
      {{genre}}  
      {% endfor %}</td>
    {% endfor %}
    <tr>

    </tr>
  </tbody>
</table>

</div>
</section>
{% endblock content %}

musicapp/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://bootswatch.com/4/united/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'music/css/style.css' %}">
    {% block head %}

    {% endblock head %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
<div class="container">
  <a class="navbar-brand" href="#">Music App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'music:album_list' %}">Albums <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'music:song_list' %}">Songs</a>
      </li>
           <li class="nav-item">
        <a class="nav-link" href="{% url 'music:band_list' %}">Bands</a>
      </li>
         <li class="nav-item">
        <a class="nav-link" href="{% url 'music:label_list' %}">Labels</a>
      </li>
            <li class="nav-item">
        <a class="nav-link" href="{% url 'music:genre_list' %}">Genres</a>
      </li>
    </ul>
  </div>
</div>
</nav>
    {% block content %}
    {% endblock content %}
</body>
</html>

musicapp/templates/music/detail.html
{% extends 'music/base.html' %}


{% block content %}
<section>
<div class="container p-4 my-4 shadowy">

   <h3 class="text-primary text-center"> {{album}}</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Tracks</th>
      <th scope="col">Band</th>
      <th scope="col">Genre</th>
      <th> Song</th>
    </tr>
  </thead>
  <tbody>
      {% for track in album.tracks.all %}
     <th scope="row">{{forloop.counter}}</th>
      <td>{{track}}</td>
      <td>{{track.band}}</td>
      <td>{% for genre in track.genre.all %}
        {{genre}} 
        {% endfor %}</td>
      <td>{{track.song}}</td>
    {% endfor %}
    <tr>

    </tr>
  </tbody>
</table>

</div>
</section>
{% endblock content %}

musicapp/templates/music/genredetail.html
{% extends 'music/base.html' %}


{% block content %}
<section>
<div class="container p-4 my-4 shadowy">

   <h3 class="text-primary text-center"> {{genre}}</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Band</th>
      <th scope="col">Website</th>
    </tr>
  </thead>
  <tbody>
     
      {% for band in genre.bands.all %}

    <tr>

        <th scope="row">{{forloop.counter}}</th>
        <td><a href="{% url 'music:band_detail' band.id %}">{{band.name}}</a></td>
        <td><a href="">{{band.website}}</a></td>
          </tr>
      {% endfor %}

   
  
  </tbody>
</table>

</div>
</section>
{% endblock content %}

musicapp/templates/music/genrelist.html
{% extends 'music/base.html' %}


{% block content %}
<section>
<div class="container p-4 my-4 shadowy">

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Genre</th>
      <th scope="col">Tracks</th>

    </tr>
  </thead>
  <tbody>
      {% for genre in genres %}
      <tr>
     <th scope="row">{{forloop.counter}}</th>
      <td><a href="{% url 'music:genre_detail' genre.slug %}">{{genre}}</a></td>
     <td>
      {% for track in genre.tracks.all %}
      <a href="{% url 'music:song_detail' track.slug %}">{{track}} </a>
      {% endfor %}
      </td>
       </tr>
    {% endfor %}
    

   
  </tbody>
</table>

</div>
</section>
{% endblock content %}

musicapp/templates/music/index.html
{% extends 'music/base.html' %}


{% block content %}
<section>
<div class="container p-4 my-4 shadowy">

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Album</th>
      <th scope="col">Band</th>
      <th scope="col">Label</th>
      <th> Release Date</th>
    </tr>
  </thead>
  <tbody>
 
    
     {% for album in albums %}
     <tr>
     <th scope="row">{{forloop.counter}}</th>
      <td><a href="{% url 'music:album_detail' album.slug %}">{{album}}</a></td>
      <td><a href="{% url 'music:band_detail' album.band.id %}">{{album.band}}</a></td>
      <td><a href="{% url 'music:label_detail' album.label.id%}">{{album.label}}</a></td>
      <td>{{album.release_date | date:"d/m/Y" }}</td>
        </tr>
    {% endfor %}
  
  </tbody>
</table>

</div>
</section>
{% endblock content %}

musicapp/templates/music/labeldetail.html
{% extends 'music/base.html' %}


{% block content %}
<section>
<div class="container p-4 my-4 shadowy">

   <h3 class="text-primary text-center"> {{label}}</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Album</th>
      <th scope="col">Label</th>
      <th scope="col">Release Date</th>
      <th>ASIN</th>
    </tr>
  </thead>
  <tbody>
     
      {% for album in label.albums.all %}
        <th scope="row">{{forloop.counter}}</th>
        <td><a href="{% url 'music:album_detail' album.slug %}">{{album.name}}</a></td>
        <td><a href="">{{album.label}}</a></td>
        <td>{{album.release_date}}</td>
        <td>{{album.asin}}</td>
      {% endfor %}

   
    <tr>

    </tr>
  </tbody>
</table>




</div>
</section>
{% endblock content %}

musicapp/templates/music/labellist.html
{% extends 'music/base.html' %}


{% block content %}
<section>
<div class="container p-4 my-4 shadowy">

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Label</th>
      <th scope="col">Website</th>
      <th scope="col">Albums</th>
    </tr>
  </thead>
  <tbody>
      {% for label in labels %}
     <th scope="row">{{forloop.counter}}</th>
      <td><a href="{% url 'music:label_detail' label.id %}">{{label}}</a></td>
      <td>{{label.website}}</td>
      <td>{% for album in label.albums.all %}
      {{album}}  
      {% endfor %}</td>
    {% endfor %}
    <tr>

    </tr>
  </tbody>
</table>

</div>
</section>
{% endblock content %}

musicapp/templates/music/songdetail.html
{% extends 'music/base.html' %}


{% block content %}
<section>
<div class="container p-4 my-4 shadowy">

   <h3 class="text-primary text-center"> {{track}}</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Album</th>
      <th scope="col">Band</th>
      <th scope="col">Genre</th>
      <th> Song</th>
    </tr>
  </thead>
  <tbody>
     <th scope="row">1</th>
      <td><a href="{% url 'music:album_detail' track.album.slug %}">{{track.album.name}}</a></td>
      <td>{{track.band}}</td>
      <td>{% for genre in track.genre.all %}
        {{genre}} 
        {% endfor %}</td>
      <td>{{track.song}}</td>
   
    <tr>

    </tr>
  </tbody>
</table>

</div>
</section>
{% endblock content %}

musicapp/templates/music/songlist.html
{% extends 'music/base.html' %}


{% block content %}
<section>
<div class="container p-4 my-4 shadowy">

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Tracks</th>
      <th scope="col">Band</th>
      <th scope="col">Label</th>
      <th> Release Date</th>
    </tr>
  </thead>
  <tbody>
      {% for track in tracks %}
     <th scope="row">{{forloop.counter}}</th>
      <td><a href="{% url 'music:song_detail' track.slug %}">{{track}}</a></td>
      <td>{{track.band}}</td>
      <td>{{track.album}}</td>
      <td>{% for genre in track.genre.all %}
      {{genre}}  
      {% endfor %}</td>
    {% endfor %}
    <tr>

    </tr>
  </tbody>
</table>

</div>
</section>
{% endblock content %}