calapp/urls.py
from django.urls import path
from . import views
# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    # path('login', auth_views.login, name="login"),
    # path('logout', auth_views.logout, name="logout"),
    # path('signup', views.signup, name="signup"),
    path('entry/<int:pk>', views.details, name="details"),
    path('entry/add', views.AddView.as_view(), name="add"),
    path('dashboard/entry/delete/<int:pk>', views.delete, name="delete"),
]

forumapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.ForumIndex.as_view(), name="index"),
    path('post/create/', views.PostCreate.as_view(), name="create_post"),
    path('post/edit/<slug>', views.PostEdit.as_view(), name="edit_post"),
    path('post/delete/<slug>', views.PostDelete.as_view(), name="delete_post"),
    path('thread/create/', views.ThreadCreate.as_view(), name="create_thread"),
    path('thread/<slug>', views.ThreadDetail.as_view(), name="thread_detail"),
    path("login/", auth_views.login,
         {'template_name': 'forum/registration/login.html'}, name="login"),
    path('logout/', auth_views.logout, {'next_page': '/forum'}, name="logout"),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('password/change/', views.change_password, name='change_password'),
    path('thread/<slug>/delete/',
         views.ThreadDelete.as_view(), name="delete_thread"),
    path('users/', views.UserList.as_view(), name="user_list"),
    path('users/edit', views.UserEdit.as_view(), name="edit_user"),
    path('comment/', views.CommentBox.as_view(), name="comment"),
    path('comment/edit/<int:pk>',
         views.CommentEdit.as_view(), name="edit_comment"),
    path('comment/delete/<int:pk>',
         views.CommentDelete.as_view(), name="delete_comment"),
    path('post/<slug>', views.PostDetails.as_view(), name="post_detail"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('places/', include('placesapp.urls')),
    path('events/', include('calapp.urls')),
    path('movies/', include('moviesapp.urls')),
    path('music/', include('musicapp.urls')),
    path('forum/', include('forumapp.urls'))
]

forumapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from .utils import get_unique_slug
from model_utils.models import TimeStampedModel


class Thread(TimeStampedModel):
    title = models.CharField(max_length=50, unique=True)
    subject = models.CharField(max_length=150, blank=True)
    slug = models.SlugField(max_length=140, unique=True, blank=True,
                            primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name="threads")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'title', 'slug')
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']


class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    is_moderator = models.BooleanField('Moderator', default=False)


class Post(TimeStampedModel):
    title = models.CharField(max_length=250)
    content = models.TextField()
    slug = models.SlugField(blank=True, primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name="posts")
    thread = models.ForeignKey(Thread,
                               on_delete=models.CASCADE,
                               related_name="posts")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'title', 'slug')
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Comment(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name="comments")
    post = models.ForeignKey("Post", on_delete=models.CASCADE,
                             related_name="comments")
    content = models.TextField()

    def __str__(self):
        return self.content

forumapp/forms.py
# users/forms.py
# from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('username', 'email')

forumapp/views.py
from django.views import generic
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from .decorators import moderator_required
from django.contrib.admin.views.decorators import staff_member_required
from .models import Post, Thread, Comment, User
from .forms import CustomUserCreationForm


# @method_decorator(moderator_required, name='dispatch')
class ForumIndex(generic.ListView):
    model = Post
    template_name = "forum/index.html"
    context_object_name = "posts"

    def get_context_data(self, **kwargs):
        context = super(ForumIndex, self).get_context_data(**kwargs)
        context['threads'] = Thread.objects.all()
        sort = self.request.GET.get('sort', None)
        sorts = {
            'oldest': '-created',
            'title': 'title',
            'reverse': '-title',
            'latest': '-modified'
        }
        if sort is None:
            print("No sort")
            context['sort'] = 'latest'
            context['sortvalue'] = sorts['latest']
        else:
            context['sort'] = sort
            context['sortvalue'] = sorts[sort]
        return context


class PostDetails(generic.DetailView):
    template_name = "forum/post_detail.html"
    model = Post
    context_object_name = "post"


class ThreadDetail(generic.DetailView):
    template_name = "forum/thread_detail.html"
    model = Thread
    context_object_name = "thread"


class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('forum:login')
    template_name = 'forum/registration/signup.html'


class CommentBox(LoginRequiredMixin, generic.CreateView):
    model = Comment
    template_name = "forum/_comment_box.html"
    fields = ['user', 'content', 'post']

    def post(self, request, *args, **kwargs):
        post_slug = request.POST.get("post", "")
        content = request.POST.get("content", "")
        bar = Comment.objects.create(
            post_id=post_slug,
            user=request.user,
            content=content)
        bar.save()
        url = reverse('forum:post_detail', kwargs={'slug': post_slug})
        return HttpResponseRedirect(url)


class PostCreate(LoginRequiredMixin, generic.CreateView):
    model = Post
    template_name = 'forum/createpost.html'
    fields = ['title', 'content', 'thread', 'user']

    def get_success_url(self, *args, **kwargs):
        return reverse('forum:post_detail', kwargs={'slug': self.object.slug})


class ThreadCreate(LoginRequiredMixin, generic.CreateView):
    model = Thread
    template_name = 'forum/createthread.html'
    fields = ['title', 'subject', 'user']

    def get_success_url(self, *args, **kwargs):
        return reverse('forum:thread_detail',
                       kwargs={'slug': self.object.slug})


class PostEdit(LoginRequiredMixin, generic.UpdateView):
    model = Post
    template_name = "forum/createpost.html"
    fields = ['title', 'content', 'thread', 'user']

    def get_queryset(self):
        base_qs = super(PostEdit, self).get_queryset()
        return base_qs.filter(user=self.request.user)

    def get_success_url(self, *args, **kwargs):
        return reverse('forum:post_detail', kwargs={'slug': self.object.slug})


class PostDelete(generic.DeleteView):
    model = Post
    success_url = reverse_lazy('forum:index')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)


class CommentEdit(generic.UpdateView):
    model = Comment
    template_name = "forum/edit_comment.html"
    fields = ['user', 'content', 'post']

    def get_success_url(self, *args, **kwargs):
        print(self.object)
        return reverse('forum:post_detail',
                       kwargs={'slug': self.object.post.slug})


class CommentDelete(generic.DeleteView):
    model = Comment

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def get_success_url(self):
        post = self.object.post
        return reverse_lazy('forum:post_detail', kwargs={'slug': post.slug})


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request,
                             'Your password was successfully updated!')
            return redirect('forum:index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'forum/registration/change_password.html', {
        'form': form
    })


@method_decorator(moderator_required, name='dispatch')
class ThreadDelete(generic.DeleteView):
    model = Thread
    success_url = reverse_lazy('forum:index')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)


@method_decorator(staff_member_required, name="dispatch")
class UserList(generic.ListView):
    model = User
    template_name = "forum/registration/user_list.html"
    context_object_name = "users"


class UserEdit(generic.View):

    def post(self, request, *args, **kwargs):
        user_id = request.POST.get("user_id", "")
        bar = User.objects.get(pk=user_id)
        bar.is_moderator = True
        bar.save()
        messages.success(request, 'Operation Successfull.')
        url = reverse('forum:index')
        return HttpResponseRedirect(url)

forumapp/templates/forum/_comment_box.html
<div class="p-4 my-2">
<div class="border p-3">
<form action="{% url 'forum:comment' %}" method="post">
{% csrf_token %}
      <div class="form-group">
    <input type="hidden" name="user" value="{{ user.id }}" class="form-control" id="exampleFormControlInput1" placeholder="">
  </div>
    <div class="form-group">
    <input type="hidden" name="post" value="{{post.slug}}" class="form-control" id="exampleFormControlInput1" placeholder="">
  </div>
    <div class="form-group">
    {% if not user.is_authenticated %}You must be logged in to type comment <a href="{% url 'forum:login' %}">Login</a> or <a href="{% url 'forum:signup' %}">Sign up</a> {% else %}
    <label for="exampleFormControlInput1"><strong>Enter your comment</strong></label> {% endif %}
     <textarea class="form-control" name="content" rows="3"{% if not user.is_authenticated %} readonly {% endif %} required>{{edit_comment}}</textarea>
  </div>
  <button class="btn btn-primary" type="submit" {% if not user.is_authenticated %}disabled {% endif %}>Submit</button>
</form>
</div>
</div>

forumapp/templates/forum/_messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

forumapp/templates/forum/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.2/materia/bootstrap.min.css" rel="stylesheet" integrity="sha384-5mtbl3D/NWE3adtPBX+YsVIhjrCzkc9MWi8qMUcsRKvXa0vuQUnGCVZEGm2Y0YYm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    {% load static %}

   <link rel="stylesheet" href="{% static 'forum/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark  bg-primary">
<div class="container">
  <a class="navbar-brand" href="{% url 'forum:index' %}">Discuz</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'forum:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>

       

      
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           {% if user.is_authenticated %}
     Hi {{ user }}!
        {% else %}
        Hi Guest
        {% endif %}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         {% if not user.is_authenticated %}
               <a href="{% url 'forum:login' %}" class="dropdown-item">Login</a>
     <a href="{% url 'forum:signup' %}" class="dropdown-item">Signup</a>
          {% else %}
          <a href="{% url 'forum:change_password' %}" class="dropdown-item">Change Passowrd</a>
          <div class="dropdown-divider"></div>
         <a href="{% url 'forum:logout' %}" class="dropdown-item">Logout</a>
          {% endif %}
          <li class="nav-item">
          {% if user.is_superuser %}
            <a href="{% url 'forum:user_list' %}" class="nav-link">Users</a>
          {% endif %}
          </li>
        </div>
      </li>
    </ul>
 
  </div>
</div>
</nav>
    {% include 'forum/_messages.html' %}
    {% block content %}
    {% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

forumapp/templates/forum/createpost.html
{% extends 'forum/base.html' %}

{% load custom_filters %}
{% block content %}
<section>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
    <div class="box border my-4 p-5 shadow">
              <h2 class="text-center my-3">Create Post</h2>
  <form class="my-2" method="post">
    {% csrf_token %}
    {% for field in form.visible_fields %}
        
        <div class="form-group">
        {% if field.name == "user" %}
            <input type="hidden" value="{{user.id}}" name="user">

            {% else %}
              {{field.name |capfirst}}
          {{ field |addcss:"form-control"}}
          {{ field.errors }}
        {% endif %}
             
           
          {% comment %} {{ field.help_text }} {% endcomment %}
        </div>
    </span>
    {% endfor %}
    <button class="btn btn-primary btn-block btn-large" type="submit">Submit</button>
  </form>
    </div>
        </div>
    </div>
</div>
</section>
{% endblock %}

forumapp/templates/forum/createthread.html
{% extends 'forum/base.html' %}

{% load custom_filters %}
{% block content %}
<section>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
    <div class="box border my-4 p-5 shadow">
              <h2 class="text-center my-3">Create Thread</h2>
  <form class="my-2" method="post">
    {% csrf_token %}
    {% for field in form.visible_fields %}
        
        <div class="form-group">
        {% if field.name == "user" %}
            <input type="hidden" value="{{user.id}}" name="user">

            {% else %}
              {{field.name |capfirst}}
          {{ field |addcss:"form-control"}}
          {{ field.errors }}
        {% endif %}
             
           
          {% comment %} {{ field.help_text }} {% endcomment %}
        </div>
    </span>
    {% endfor %}
    <button class="btn btn-primary btn-block btn-large" type="submit">Submit</button>
  </form>
    </div>
        </div>
    </div>
</div>
</section>
{% endblock %}

forumapp/templates/forum/edit_comment.html
{% extends 'forum/base.html' %}
{% load custom_filters %}
{% block content %}
<section class="my-4">
    <div class="container">
        <div class="row  justify-content-center">
            <div class="col-6">
            <form class="my-2" method="post">
    {% csrf_token %}
    {% for field in form.visible_fields %}
        
        <div class="form-group">
        {% if field.name == "user" %}
            <input type="hidden" value="{{user.id}}" name="user">
    {% elif field.name == "post" %}
    <input type="hidden" value="{{comment.post.slug}}" name="post">
            {% else %}
              {{field.name |capfirst}}
          {{ field |addcss:"form-control"}}
          {{ field.errors }}
        {% endif %}
             
           
          {% comment %} {{ field.help_text }} {% endcomment %}
        </div>
    </span>
    {% endfor %}
    <button class="btn btn-primary btn-block btn-large" type="submit">Submit</button>
  </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

forumapp/templates/forum/index.html
{% extends 'forum/base.html' %}
{% load custom_filters %}
{% block content %}

<section class="my-5">
    <div class="container">
        <div class="row">
<form action="" method="get">
 <div class="form-group">
    <label>Sort By</label>
    <select onchange="this.form.submit()" name="sort" class="form-control" id="exampleFormControlSelect1">
      <option style="display:none;" value="{{sort}}">{{sort |capfirst}}</option>
      <option value="latest">Latest</option>
      <option value="title">Title</option>
      <option value="oldest">Oldest</option>
      <option value="reverse">Reverse</option>  
    </select>
  </div> 
</form> 
        </div>
        <div class="row">
            <div class="col-md-8">
             {% for post in posts|sort_by:sortvalue %}
                <div class="border postbox shadowy my-3 p-3">
                    <a class="nodecor" href="{% url 'forum:post_detail' post.slug %}">
                        <h4 class="text-primary font-weight-bold">{{post}}</h4>
                        <p class="text-black">{{post.content |truncatechars_html:200}}</p>
                    </a>
                </div>
             {% endfor %}
            </div>
            <div class="col-md-4">
                <div class="border my-3 p-3 shadowy">
                    {% if user.is_authenticated %}
                    <a href="{% url 'forum:create_post' %}" class="btn btn-block btn-primary">Start a Discussion</a>
                    <a href="{% url 'forum:create_thread' %}" class="btn btn-block btn-warning">Start a Topic</a>
                    {% else %}
                    Please <a href="{% url 'forum:login' %}">Login</a> or <a href="{% url 'forum:signup' %}">Sign up</a> to access more features.
                    {% endif %}
                    
                    <hr>
                  
                    {% for thread in threads %}
                        <p><span class="dot d-flex"  style="background:{{"# "|rand_color}}"><strong class="ali"><a class="nodecor text-black" href="{% url 'forum:thread_detail' thread.slug %}">{{thread}}</a></strong></span></p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

forumapp/templates/forum/post_detail.html
{% extends 'forum/base.html' %}


{% block content %}


<div class="jumbotron">
<div class="container">
    <a href="{% url 'forum:thread_detail' post.thread.slug %}"><h5 class="badge badge-primary badge-big">{{post.thread.title}}</h5></a>
  <h3 class="font-weight-bold">{{post.title}}</h3>
{% if user == post.user %}
<div class="text-right">
<a href="{% url 'forum:edit_post' post.slug %}" class="btn btn-warning">Edit</a>
<a href="{% url 'forum:delete_post' post.slug %}" class="btn btn-danger">Delete</a>
</div>
{% endif %}

</div>
</div>
<section>
<div class="container">
<div class="row">
<div class="col-md-8">
<div class="border p-3 lightbg">
<p>Post by <strong>{{post.user |capfirst}}</strong> | {{post.modified}} {% if  post.modified|date:"g:i a" == post.created|date:"g:i a"  %} {% else %}<strong>(Edited)</strong>{% endif %}</p>

<p class="text-justify">
{{post.content}}
</p>
</div>
<br>
{% if post.comments.all %}
<p class="text-line text-center"><span><strong>{{post.comments.count}} COMMENTS</strong></span></p>
{% else %}
    <p class="text-line text-center"><span><strong>BE THE FIRST ONE TO COMMENT</strong></span></p>
    
{% endif %}

<br>
{% for comment in post.comments.all %}
   <div class="p-3 my-2">
     <div>
     <span class="text-left"><strong>{{comment.user |capfirst}}</strong> | {{comment.created}} {% if  comment.modified|date:"g:i a" == comment.created|date:"g:i a"  %} {% else %}<strong>(Edited)</strong>{% endif %}</span>
     {% if user == comment.user %}
     <span class="float-right">
      <a href="{% url 'forum:edit_comment' comment.id %}" class="badge badge-primary">Edit</a>
      <a href="{% url 'forum:delete_comment' comment.id %}" class="badge badge-danger">Delete</a>
     </span>
     {% endif %}
     <div class="clearfix"></div>
     </div>
     <p class="text-justify my-2">{{comment.content}}</p>
     <hr>
   </div>
{% endfor %}

{% include 'forum/_comment_box.html'  with post=post edit_comment=edit_comment%}
</div>
</div>

</div>
</section>


{% endblock content %}

forumapp/templates/forum/thread_detail.html
{% extends 'forum/base.html' %}

{% block content %}

<section>
<div class="jumbotron">
 <div class="container text-center">
  <h1 class="display-5"><strong class="text-primary">{{thread.title}}</strong></h1>
  <p class="lead">{{thread.subject}}</p>
{% if user.is_moderator %}
<div class="text-right">
<a href="{% url 'forum:delete_thread' thread.pk%}" class="btn btn-danger">Delete</a>
</div>
{% endif %}
 </div>
</div>
</section>
<section>
<div class="container">
    <div class="row">
              <div class="col-md-12">
            {% if thread.posts.all %}
             {% for post in thread.posts.all %}
                <div class="border postbox shadowy my-3 p-3">
                    <a class="nodecor" href="{% url 'forum:post_detail' post.slug %}">
                        <h4 class="text-primary font-weight-bold">{{post}}</h4>
                        <p class="text-black">{{post.content |truncatechars_html:200}}</p>
                    </a>
                </div>
             {% endfor %}
            {% else %}
                <h3 class="text-center">No Posts Yet</h3>
               <div class="text-center">
                <a href="{% url 'forum:create_post' %}" class="btn btn-primary">Create a New Post</a>
            
               </div>
               {% endif %}
            </div>
    </div>
</div>
</section>
{% endblock content %}